title: 技术分享
description: 分享技术，记录生活
theme: minima

# GitHub配置
github_username: barney-cs
repository: barney-cs/skills-github-pages

# Gitalk配置
gitalk:
  enable: true
  repo: skills-github-pages    # 存储评论的仓库名
  owner: barney-cs    # 你的 GitHub 用户名
  admin: ['barney-cs']    # 管理员用户名列表
  language: zh-CN    # 设置语言为中文

# 主题设置
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
